<?php

namespace PackageVersions;

/**
 * This class is generated by ocramius/package-versions, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 */
final class Versions
{
    const ROOT_PACKAGE_NAME = 'fastest/fastest';
    const VERSIONS = array (
  'composer/semver' => '1.4.2@c7cb9a2095a074d131b65a8a0cd294479d785573',
  'doctrine/annotations' => 'v1.6.0@c7f2050c68a9ab0bdb0f98567ec08d80ea7d24d5',
  'doctrine/lexer' => 'v1.0.1@83893c552fd2045dd78aef794c31e694c37c0b8c',
  'egulias/email-validator' => '2.1.4@8790f594151ca6a2010c6218e09d96df67173ad3',
  'friendsofphp/php-cs-fixer' => 'v2.11.1@ad94441c17b8ef096e517acccdbf3238af8a2da8',
  'guzzlehttp/psr7' => '1.4.2@f5b8a8512e2b58b0071a7280e39f14f72e05d87c',
  'intervention/image' => '2.4.1@3603dbcc9a17d307533473246a6c58c31cf17919',
  'kriswallsmith/assetic' => 'v1.4.0@e911c437dbdf006a8f62c2f59b15b2d69a5e0aa1',
  'league/flysystem' => '1.0.44@168dbe519737221dc87d17385cde33073881fd02',
  'lnked/pubsub' => 'dev-master@1b4c3e25e9e37e8de6024ef9fd7f20241f21a34c',
  'lnked/q' => 'dev-master@22e159461b5b4bca29bc1a2c7e1f034ee3a599a8',
  'matthiasmullie/minify' => '1.3.60@ab7fea80ce5ce6549baaf272bc8bd926a7e08f90',
  'matthiasmullie/path-converter' => '1.1.1@3082a6838be02b930239a97d38b5c9da4d693aca',
  'matthiasmullie/scrapbook' => '1.4.6@044ff954e41579ff922ee3341b1695d12bb04840',
  'paragonie/random_compat' => 'v2.0.12@258c89a6b97de7dfaf5b8c7607d0478e236b04fb',
  'php-cs-fixer/diff' => 'v1.3.0@78bb099e9c16361126c86ce82ec4405ebab8e756',
  'phpfastcache/phpfastcache' => '6.1.2@0a8acb7d6e80b84a6bfdd7f8fb011097b0ce2a15',
  'phpoffice/phpspreadsheet' => '1.2.1@36acc372875c4d894dc093825ce4f62209db5a76',
  'prewk/xml-streamer' => '0.5.0@d375929a7d96b9dc0246af270209465c7dd4de5b',
  'psr/cache' => '1.0.1@d11b50ad223250cf17b86e38383413f5a6764bf8',
  'psr/http-message' => '1.0.1@f6561bf28d520154e4b0ec72be95418abe6d9363',
  'psr/log' => '1.0.2@4ebe3a8bf773a19edfe0a84b6585ba3d401b724d',
  'psr/simple-cache' => '1.0.1@408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
  'samdark/sitemap' => '2.2.0@c897f7a9cb0882e34169359a5f1f715e05b34d67',
  'smarty/smarty' => 'v3.1.31@c7d42e4a327c402897dd587871434888fde1e7a9',
  'spomky-labs/base64url' => 'v1.0.2@ef6d5fb93894063d9cee996022259fd08d6646ea',
  'swiftmailer/swiftmailer' => 'v6.0.2@412333372fb6c8ffb65496a2bbd7321af75733fc',
  'symfony/console' => 'v3.4.8@d4bb70fa24d540c309d88a9d6e43fb2d339b1fbf',
  'symfony/debug' => 'v3.4.8@9cf7c2271cfb89ef9727db1b740ca77be57bf9d7',
  'symfony/event-dispatcher' => 'v3.4.8@fdd5abcebd1061ec647089c6c41a07ed60af09f8',
  'symfony/filesystem' => 'v3.4.8@253a4490b528597aa14d2bf5aeded6f5e5e4a541',
  'symfony/finder' => 'v3.4.8@bd14efe8b1fabc4de82bf50dce62f05f9a102433',
  'symfony/options-resolver' => 'v3.4.8@f3109a6aedd20e35c3a33190e932c2b063b7b50e',
  'symfony/polyfill-iconv' => 'v1.7.0@bd515d8f392730c833bc1ba993a4f598da64fa5b',
  'symfony/polyfill-intl-grapheme' => 'v1.7.0@9a3548340d338baf5f263bbc171f138045ab547e',
  'symfony/polyfill-intl-normalizer' => 'v1.7.0@4e5fca97448b2e5ac785e1c55b2f6a152f61a4da',
  'symfony/polyfill-mbstring' => 'v1.7.0@78be803ce01e55d3491c1397cf1c64beb9c1b63b',
  'symfony/polyfill-php70' => 'v1.7.0@3532bfcd8f933a7816f3a0a59682fc404776600f',
  'symfony/polyfill-php72' => 'v1.7.0@8eca20c8a369e069d4f4c2ac9895144112867422',
  'symfony/process' => 'v3.4.8@4b7d64e852886319e93ddfdecff0d744ab87658b',
  'symfony/stopwatch' => 'v3.4.8@eb17cfa072cab26537ac37e9c4ece6c0361369af',
  'twig/twig' => 'v2.4.8@7b604c89da162034bdf4bb66310f358d313dd16d',
  'voku/portable-utf8' => '5.0.5@778199ac292e17497afb221c2ddd044429fbb229',
  'voronkovich/sberbank-acquiring-client' => 'v1.1.3@7c0148166b7cb7117a95b16c4b77e58be5e5ade6',
  'webonyx/graphql-php' => 'v0.11.6@f438a726cd523bc584e78d866eca270165c42fd5',
  'doctrine/instantiator' => '1.1.0@185b8868aa9bf7159f5f953ed5afb2d7fcdc3bda',
  'jean85/pretty-package-versions' => '1.1@d457344b6a035ef99236bdda4729ad7eeb233f54',
  'krok/phpquery' => '0.9.5.3@ee3c1d1a7a9f1ccb31d4823ad62ca388d2555e9d',
  'myclabs/deep-copy' => '1.7.0@3b8a3a99ba1f6a3952ac2747d989303cbd6b7a3e',
  'nette/bootstrap' => 'v2.4.5@804925787764d708a7782ea0d9382a310bb21968',
  'nette/di' => 'v2.4.11@a300c8b8e8549595ab90c04d8ee21b8b2a5a88f9',
  'nette/finder' => 'v2.4.1@4d43a66d072c57d585bf08a3ef68d3587f7e9547',
  'nette/neon' => 'v2.4.2@9eacd50553b26b53a3977bfb2fea2166d4331622',
  'nette/php-generator' => 'v3.0.3@18a26e9c302ce98b7a573fae8c6032a6909339e5',
  'nette/robot-loader' => 'v3.0.3@92d4b40b49d5e2d9e37fc736bbcebe6da55fa44a',
  'nette/utils' => 'v2.5.1@8a85ce76298c8a8941f912b8fa3ee93ca17d2ebc',
  'nikic/php-parser' => 'v3.1.5@bb87e28e7d7b8d9a7fda231d37457c9210faf6ce',
  'ocramius/package-versions' => '1.3.0@4489d5002c49d55576fa0ba786f42dbb009be46f',
  'phar-io/manifest' => '1.0.1@2df402786ab5368a0169091f61a7c1e0eb6852d0',
  'phar-io/version' => '1.0.1@a70c0ced4be299a63d32fa96d9281d03e94041df',
  'phpdocumentor/reflection-common' => '1.0.1@21bdeb5f65d7ebf9f43b1b25d404f87deab5bfb6',
  'phpdocumentor/reflection-docblock' => '4.3.0@94fd0001232e47129dd3504189fa1c7225010d08',
  'phpdocumentor/type-resolver' => '0.4.0@9c977708995954784726e25d0cd1dddf4e65b0f7',
  'phpspec/prophecy' => '1.7.6@33a7e3c4fda54e912ff6338c48823bd5c0f0b712',
  'phpstan/phpdoc-parser' => '0.2@02f909f134fe06f0cd4790d8627ee24efbe84d6a',
  'phpstan/phpstan' => '0.9.2@e59541bcc7cac9b35ca54db6365bf377baf4a488',
  'phpunit/dbunit' => '3.0.3@0fa4329e490480ab957fe7b1185ea0996ca11f44',
  'phpunit/php-code-coverage' => '5.3.2@c89677919c5dd6d3b3852f230a663118762218ac',
  'phpunit/php-file-iterator' => '1.4.5@730b01bc3e867237eaac355e06a36b85dd93a8b4',
  'phpunit/php-text-template' => '1.2.1@31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
  'phpunit/php-timer' => '1.0.9@3dcf38ca72b158baf0bc245e9184d3fdffa9c46f',
  'phpunit/php-token-stream' => '2.0.2@791198a2c6254db10131eecfe8c06670700904db',
  'phpunit/phpunit' => '6.5.8@4f21a3c6b97c42952fd5c2837bb354ec0199b97b',
  'phpunit/phpunit-mock-objects' => '5.0.6@33fd41a76e746b8fa96d00b49a23dadfa8334cdf',
  'sebastian/code-unit-reverse-lookup' => '1.0.1@4419fcdb5eabb9caa61a27c7a1db532a6b55dd18',
  'sebastian/comparator' => '2.1.3@34369daee48eafb2651bea869b4b15d75ccc35f9',
  'sebastian/diff' => '2.0.1@347c1d8b49c5c3ee30c7040ea6fc446790e6bddd',
  'sebastian/environment' => '3.1.0@cd0871b3975fb7fc44d11314fd1ee20925fce4f5',
  'sebastian/exporter' => '3.1.0@234199f4528de6d12aaa58b612e98f7d36adb937',
  'sebastian/global-state' => '2.0.0@e8ba02eed7bbbb9e59e43dedd3dddeff4a56b0c4',
  'sebastian/object-enumerator' => '3.0.3@7cfd9e65d11ffb5af41198476395774d4c8a84c5',
  'sebastian/object-reflector' => '1.1.1@773f97c67f28de00d397be301821b06708fca0be',
  'sebastian/recursion-context' => '3.0.0@5b0cd723502bac3b006cbf3dbf7a1e3fcefe4fa8',
  'sebastian/resource-operations' => '1.0.0@ce990bb21759f94aeafd30209e8cfcdfa8bc3f52',
  'sebastian/version' => '2.0.1@99732be0ddb3361e16ad77b68ba41efc8e979019',
  'squizlabs/php_codesniffer' => '3.2.3@4842476c434e375f9d3182ff7b89059583aa8b27',
  'symfony/yaml' => 'v3.4.8@a42f9da85c7c38d59f5e53f076fe81a091f894d0',
  'theseer/tokenizer' => '1.1.0@cb2f008f3f05af2893a87208fe6a6c4985483f8b',
  'webmozart/assert' => '1.3.0@0df1908962e7a3071564e857d86874dad1ef204a',
  'fastest/fastest' => 'dev-dev@7446cb31f66afdb209b4a9f1afc33d1e451f8dd6',
);

    private function __construct()
    {
    }

    /**
     * @throws \OutOfBoundsException if a version cannot be located
     */
    public static function getVersion(string $packageName) : string
    {
        if (isset(self::VERSIONS[$packageName])) {
            return self::VERSIONS[$packageName];
        }

        throw new \OutOfBoundsException(
            'Required package "' . $packageName . '" is not installed: cannot detect its version'
        );
    }
}
