<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname(dirname($vendorDir)));

return array(
    'phpQuery' => array($vendorDir . '/krok/phpquery/src'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
    'Assetic' => array($vendorDir . '/kriswallsmith/assetic/src'),
);
